### ISSUE TITLE
failed tests with pypy3

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [leapfrogonline/rstr#20]
```
>>> Test phase: dev-python/rstr-3.1.0
 * pypy3: running distutils-r1_run_phase python_test
test_convenience_function (test_package_level_access.TestPackageLevelFunctions) ... ok
test_rstr (test_package_level_access.TestPackageLevelFunctions) ... ok
test_xeger (test_package_level_access.TestPackageLevelFunctions) ... ERROR
test_add_alphabet (test_rstr.TestCustomAlphabets) ... ok
test_alphabet_at_instantiation (test_rstr.TestCustomAlphabets) ... ok
test_all_digits (test_rstr.TestDigits) ... ok
test_digits_exclude (test_rstr.TestDigits) ... ok
test_digits_include (test_rstr.TestDigits) ... ok
test_letters (test_rstr.TestLetters) ... ok
test_letters_exclude (test_rstr.TestLetters) ... ok
test_letters_include (test_rstr.TestLetters) ... ok
test_nondigits (test_rstr.TestNondigits) ... ok
test_nondigits_exclude (test_rstr.TestNondigits) ... ok
test_nondigits_include (test_rstr.TestNondigits) ... ok
test_alphabet_as_list (test_rstr.TestRstr) ... ok
test_custom_alphabet (test_rstr.TestRstr) ... ok
test_end_range_no_start_range (test_rstr.TestRstr) ... ok
test_exclude (test_rstr.TestRstr) ... ok
test_exclude_as_list (test_rstr.TestRstr) ... ok
test_include (test_rstr.TestRstr) ... ok
test_include_as_list (test_rstr.TestRstr) ... ok
test_include_specific_length (test_rstr.TestRstr)
Verify including characters doesn't make the string longer than intended. ... ok
test_length_range (test_rstr.TestRstr) ... ok
test_raise_exception_if_include_and_exclude_parameters_contain_same_character (test_rstr.TestRstr) ... ok
test_specific_length (test_rstr.TestRstr) ... ok
test_alphabet_as_list (test_rstr.TestSystemRandom) ... ok
test_custom_alphabet (test_rstr.TestSystemRandom) ... ok
test_end_range_no_start_range (test_rstr.TestSystemRandom) ... ok
test_exclude (test_rstr.TestSystemRandom) ... ok
test_exclude_as_list (test_rstr.TestSystemRandom) ... ok
test_include (test_rstr.TestSystemRandom) ... ok
test_include_as_list (test_rstr.TestSystemRandom) ... ok
test_include_specific_length (test_rstr.TestSystemRandom)
Verify including characters doesn't make the string longer than intended. ... ok
test_length_range (test_rstr.TestSystemRandom) ... ok
test_raise_exception_if_include_and_exclude_parameters_contain_same_character (test_rstr.TestSystemRandom) ... ok
test_specific_length (test_rstr.TestSystemRandom) ... ok
test_unambiguous (test_rstr.TestUnambiguous) ... ok
test_unambiguous_exclude (test_rstr.TestUnambiguous) ... ok
test_unambiguous_include (test_rstr.TestUnambiguous) ... ok
test_backreference (test_xeger.TestXeger) ... ERROR
test_carot (test_xeger.TestXeger) ... ERROR
test_character_group (test_xeger.TestXeger) ... ERROR
test_digit (test_xeger.TestXeger) ... ERROR
test_dollarsign (test_xeger.TestXeger) ... ERROR
test_dot (test_xeger.TestXeger)
Verify that the dot character doesn't produce newlines. ... ERROR
test_literal_with_range_repeat (test_xeger.TestXeger) ... ERROR
test_literal_with_repeat (test_xeger.TestXeger) ... ERROR
test_literals (test_xeger.TestXeger) ... ERROR
test_lookahead (test_xeger.TestXeger) ... ERROR
test_lookbehind (test_xeger.TestXeger) ... ERROR
test_negation_group (test_xeger.TestXeger) ... ERROR
test_nondigits (test_xeger.TestXeger) ... ERROR
test_nonword (test_xeger.TestXeger) ... ERROR
test_not_literal (test_xeger.TestXeger) ... ERROR
test_or (test_xeger.TestXeger) ... ERROR
test_or_with_subpattern (test_xeger.TestXeger) ... ERROR
test_range (test_xeger.TestXeger) ... ERROR
test_word (test_xeger.TestXeger) ... ERROR
test_zero_or_more_greedy (test_xeger.TestXeger) ... ERROR
test_zero_or_more_non_greedy (test_xeger.TestXeger) ... ERROR

======================================================================
ERROR: test_xeger (test_package_level_access.TestPackageLevelFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_package_level_access.py", line 13, in test_xeger
    assert re.match(r'^foo[\d]{10}bar$', rstr.xeger('^foo[\d]{10}bar$'))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '6'

======================================================================
ERROR: test_backreference (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 90, in test_backreference
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '26'

======================================================================
ERROR: test_carot (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 66, in test_carot
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '6'

======================================================================
ERROR: test_character_group (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 62, in test_character_group
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '14'

======================================================================
ERROR: test_digit (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 26, in test_digit
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '14'

======================================================================
ERROR: test_dollarsign (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 70, in test_dollarsign
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '17'

======================================================================
ERROR: test_dot (test_xeger.TestXeger)
Verify that the dot character doesn't produce newlines.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 22, in test_dot
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '42'

======================================================================
ERROR: test_literal_with_range_repeat (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 38, in test_literal_with_range_repeat
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '17'

======================================================================
ERROR: test_literal_with_repeat (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 34, in test_literal_with_repeat
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '42'

======================================================================
ERROR: test_literals (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 13, in test_literals
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '17'

======================================================================
ERROR: test_lookahead (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 82, in test_lookahead
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '17'

======================================================================
ERROR: test_lookbehind (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 86, in test_lookbehind
    assert re.search(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '4'

======================================================================
ERROR: test_negation_group (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 78, in test_negation_group
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '14'

======================================================================
ERROR: test_nondigits (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 30, in test_nondigits
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '14'

======================================================================
ERROR: test_nonword (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 46, in test_nonword
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '14'

======================================================================
ERROR: test_not_literal (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 74, in test_not_literal
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '21'

======================================================================
ERROR: test_or (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 50, in test_or
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '7'

======================================================================
ERROR: test_or_with_subpattern (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 54, in test_or_with_subpattern
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '26'

======================================================================
ERROR: test_range (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 58, in test_range
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '14'

======================================================================
ERROR: test_word (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 42, in test_word
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '14'

======================================================================
ERROR: test_zero_or_more_greedy (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 94, in test_zero_or_more_greedy
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '42'

======================================================================
ERROR: test_zero_or_more_non_greedy (test_xeger.TestXeger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/tests/test_xeger.py", line 98, in test_zero_or_more_non_greedy
    assert re.match(pattern, self.rs.xeger(pattern))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 67, in xeger
    result = self._build_string(parsed)
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 74, in _build_string
    newstr.append(self._handle_state(state))
  File "/var/tmp/portage/dev-python/rstr-3.1.0/work/rstr-3.1.0/rstr/xeger.py", line 82, in _handle_state
    return self._cases[opcode](value)
KeyError: '41'

----------------------------------------------------------------------
Ran 60 tests in 0.288s

FAILED (errors=22)
```

See https://bugs.gentoo.org/835474

**Comment by bjmc** [comment]
Thanks for your report!

Can you provide any more detail on your test runner setup? The Gentoo project must be doing something differently because these tests are [passing on CircleCI](https://app.circleci.com/pipelines/github/leapfrogonline/rstr/17/workflows/eb24e966-02a3-4301-b88e-18c913dd82ae/jobs/18?invite=true#step-102-51).

**Comment by Alessandro-Barbieri** [comment]
It's using pypy-7.3.8

**Comment by bjmc** [comment]
Thanks. If I have some time this week, I'll take a look. Maybe we should be testing against specific PyPy versions like we do for CPython...
